# import os
# import google.generativeai as genai

# # --------------------------------------------------
# # Configure Gemini API
# # --------------------------------------------------

# GEMINI_API_KEY = os.getenv(
#     "GEMINI_API_KEY"
# )

# if not GEMINI_API_KEY:
#     raise ValueError(
#         "GEMINI_API_KEY is not set in environment variables."
#     )

# genai.configure(
#     api_key=GEMINI_API_KEY
# )

# # --------------------------------------------------
# # Initialize Model
# # --------------------------------------------------

# MODEL_NAME = os.getenv(
#     "MODEL_NAME",
#     "gemini-2.5-flash"
# )

# model = genai.GenerativeModel(
#     MODEL_NAME
# )

# # --------------------------------------------------
# # Generate Response
# # --------------------------------------------------

# def generate_response(
#     prompt: str,
#     temperature: float = 0.3,
#     max_output_tokens: int = 2048,
# ):
#     """
#     Generate a response using the Gemini model.

#     Args:
#         prompt (str): The input prompt.
#         temperature (float): Controls randomness.
#         max_output_tokens (int): Maximum output length.

#     Returns:
#         str: Generated response text.
#     """

#     try:
#         response = model.generate_content(
#             prompt,
#             generation_config={
#                 "temperature": temperature,
#                 "max_output_tokens": max_output_tokens,
#             },
#         )

#         if (
#             hasattr(
#                 response,
#                 "text",
#             )
#             and response.text
#         ):
#             return response.text.strip()

#         return (
#             "No response generated by the AI model."
#         )

#     except Exception as error:
#         print(
#             "[Gemini Error]",
#             str(error),
#         )

#         return (
#             "Sorry, I encountered an error while generating the response."
#         )
    


import os
import google.generativeai as genai


class GeminiModel:
    def __init__(self):
        api_key = os.getenv(
            "GEMINI_API_KEY"
        )

        if not api_key:
            raise ValueError(
                "Missing GEMINI_API_KEY"
            )

        genai.configure(
            api_key=api_key
        )

        self.model = (
            genai.GenerativeModel(
                os.getenv(
                    "MODEL_NAME",
                    "gemini-2.5-flash",
                )
            )
        )

    def generate_response(
        self,
        prompt: str,
        temperature: float = 0.3,
        max_output_tokens: int = 2048,
    ) -> str:
        try:
            response = (
                self.model.generate_content(
                    prompt,
                    generation_config={
                        "temperature": temperature,
                        "max_output_tokens": max_output_tokens,
                    },
                )
            )

            return (
                response.text.strip()
                if hasattr(
                    response,
                    "text",
                )
                else "No response generated."
            )

        except Exception as e:
            print(
                f"[Gemini Error] {e}"
            )

            return (
                "AI service temporarily unavailable."
            )


# Global singleton instance
gemini = GeminiModel()


# Helper function
def generate_response(
    prompt: str,
    temperature: float = 0.3,
    max_output_tokens: int = 2048,
):
    return gemini.generate_response(
        prompt=prompt,
        temperature=temperature,
        max_output_tokens=max_output_tokens,
    )
    